# Backend Dockerfile
FROM node:23.11-alpine

# Set working directory
WORKDIR /usr/src/cache

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
RUN mkdir /usr/src/app && \
    apk add --no-cache rsync=3.4.0-r0 && \
    rm -rf /var/cache/apk/*

WORKDIR /usr/src/app

COPY . .

# Build the application
# RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["npm", "start"] 