# Backend Dockerfile
FROM node:23.11-alpine

WORKDIR /usr/src/cache
# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Set working directory

# Copy source code
RUN mkdir /usr/src/app && apk update && apk add rsync
WORKDIR /usr/src/app

COPY . .

# Build the application (if using TypeScript or other build steps)
# RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["npm", "start"] 